# Generated by Django 4.2.1 on 2023-06-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_alter_userrole_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserGroup',
        ),
    ]
