# Generated by Django 4.2.1 on 2023-06-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_userrole_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
    ]
