# Generated by Django 4.2.1 on 2023-06-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usergroup_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='role',
            new_name='group',
        ),
    ]
