# Generated by Django 4.0.3 on 2023-06-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_role_usergroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
